### ISSUE TITLE
jest-watch-yarn-workspaces: Support new structure of the "workspaces" property

### ISSUE THREAD

**Issue by busybeaver** [cameronhunter/jest-watch-directories#1]
Hi,

starting from yarn 1.4.2, the `workspaces` property in the _package.json_ file can have a different structure (if the nohoist feature should be used; see details [here](https://yarnpkg.com/blog/2018/02/15/nohoist/)):

```
"workspaces": {
  "packages": ["packages/*"],
  "nohoist": ["**/react-native", "**/react-native/**"]
}
```

While the old structure of just being an array is still valid, I suggest to support both formats in _jest-watch-yarn-workspaces_. See also the type definitions for `workspaces` property: [[1](https://github.com/yarnpkg/yarn/blob/e905f7479ef8ea5ecbc5ca115f0287be709c7d58/src/types.js#L146),[2](https://github.com/yarnpkg/yarn/blob/e905f7479ef8ea5ecbc5ca115f0287be709c7d58/src/types.js#L54-L57)].

From my understanding, [this line](https://github.com/cameronhunter/jest-watch-directories/blob/ee1c63ab66785b16ba7d2454881d1f9960e96a4b/packages/jest-watch-yarn-workspaces/index.js#L15) would need some changes... maybe something like:

```js
function getDirectories(packageConfig) {
  const yarnWorkspaces = packageConfig.workspaces;
  if (Array.isArray(yarnWorkspaces)) return yarnWorkspaces;
  if (yarnWorkspaces && Array.isArray(yarnWorkspaces.packages)) return yarnWorkspaces.packages;
  return undefined;
}
```

**Comment by cameronhunter** [comment]
Published as [v1.1.0](https://github.com/cameronhunter/jest-watch-directories/releases/tag/v1.1.0)
